#!/bin/bash

cd $(dirname $0)/..

/bin/sed -i "s/NGINX_SERVER_REPLACEME/${NGINX_SERVER_NAME}/" /etc/nginx/sites-available/nginx_docker_hub_listener.conf

service nginx restart

gunicorn -w 4 -u gunicorn -b 127.0.0.1:4000 docker_hub_listener:app 2>&1
